"""Referrer_ID added

Revision ID: e6bac45c5147
Revises: 255a47afcbb0
Create Date: 2024-03-22 09:45:50.536347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bac45c5147'
down_revision: Union[str, None] = '255a47afcbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_referral_code')
    op.add_column('user', sa.Column('referrer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'referrer_id')
    op.create_table('user_referral_code',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referral_code_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referral_code.id'], name='user_referral_code_referral_code_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_referral_code_user_id_fkey')
    )
    # ### end Alembic commands ###
